var files =
[
    [ "engine/ChunkedList.h", "ChunkedList_8h.html", null ],
    [ "engine/FreeList.h", "FreeList_8h.html", null ],
    [ "engine/InputFormatter.cc", "InputFormatter_8cc.html", "InputFormatter_8cc" ],
    [ "engine/main.cc", "main_8cc.html", "main_8cc" ],
    [ "engine/Master.cc", "Master_8cc.html", "Master_8cc" ],
    [ "engine/Master.h", "Master_8h.html", "Master_8h" ],
    [ "engine/MsgBuffer.h", "MsgBuffer_8h.html", null ],
    [ "engine/Node.cc", "Node_8cc.html", "Node_8cc" ],
    [ "engine/OutputFormatter.cc", "OutputFormatter_8cc.html", "OutputFormatter_8cc" ],
    [ "engine/Receiver.cc", "Receiver_8cc.html", null ],
    [ "engine/Receiver.h", "Receiver_8h.html", "Receiver_8h" ],
    [ "engine/Sender.cc", "Sender_8cc.html", null ],
    [ "engine/Sender.h", "Sender_8h.html", "Sender_8h" ],
    [ "engine/Utility.h", "Utility_8h.html", "Utility_8h" ],
    [ "engine/Worker.cc", "Worker_8cc.html", "Worker_8cc" ],
    [ "engine/Worker.h", "Worker_8h.html", "Worker_8h" ],
    [ "example/PageRankVertex.cc", "PageRankVertex_8cc.html", "PageRankVertex_8cc" ],
    [ "include/Addr.h", "Addr_8h.html", "Addr_8h" ],
    [ "include/Aggregator.h", "Aggregator_8h.html", null ],
    [ "include/AggregatorBase.h", "AggregatorBase_8h.html", null ],
    [ "include/GenericArrayIterator.h", "GenericArrayIterator_8h.html", null ],
    [ "include/GenericLinkIterator.h", "GenericLinkIterator_8h.html", "GenericLinkIterator_8h" ],
    [ "include/Graph.h", "Graph_8h.html", "Graph_8h" ],
    [ "include/GraphLite.h", "GraphLite_8h.html", null ],
    [ "include/InputFormatter.h", "InputFormatter_8h.html", "InputFormatter_8h" ],
    [ "include/Node.h", "Node_8h.html", "Node_8h" ],
    [ "include/OutputFormatter.h", "OutputFormatter_8h.html", null ],
    [ "include/Vertex.h", "Vertex_8h.html", null ],
    [ "include/VertexBase.h", "VertexBase_8h.html", null ]
];